### ISSUE TITLE
verify signature

### ISSUE THREAD

**Issue by marqi** [ThomasHabets/simple-tpm-pk11#18]
I'm using the stpm-sign command to sign files, but how can I verify that the signature is authentic?

**Comment by ThomasHabets** [comment]
First of all, what are you trying to achieve? Does your use case have anything to do with pkcs11 or SSH, or are you just trying to sign files for later validation?

It's not a good idea to use these primitive functions to sign and verify. Instead you should use something like GPG and get certificates and more higher level stuff.

I've not set up GPG with TPM chips though.

But I guess the short answer is that I haven't implemented the signature verification.

**Comment by ThomasHabets** [comment]
Done in f6fb14a7d7d915816e9eb6ac03edaa217ba1ec65
