### ISSUE TITLE
failure to read public key

### ISSUE THREAD

**Issue by jdkbx** [ThomasHabets/simple-tpm-pk11#19]
Hey,

I have been trying to get this to work on gentoo. Unfortuneatly the command

ssh-keygen -D libsimple-tpm-pk11.so
returns
no keys
cannot read public key from pkcs11

I am on a lenovo thinkpad x220i. I already reseted the tpm and took ownership again, but still the same issue. stpm-sign produces output that seems OK. 

The logfile only contains
Mon Apr  6 21:50:42 2015 DEBUG C_GetFunctionList()
Mon Apr  6 21:50:42 2015 DEBUG C_Initialize()
Mon Apr  6 21:50:42 2015 DEBUG C_GetInfo()
Mon Apr  6 21:50:42 2015 DEBUG C_GetSlotList()
Mon Apr  6 21:50:42 2015 DEBUG C_GetSlotList()
Mon Apr  6 21:50:42 2015 DEBUG C_GetTokenInfo()
Mon Apr  6 21:50:46 2015 DEBUG C_OpenSession()
Mon Apr  6 21:50:46 2015 DEBUG C_FindObjectsInit()
Mon Apr  6 21:50:46 2015 DEBUG C_FindObjects()
Mon Apr  6 21:50:46 2015 DEBUG C_GetAttributeValue()
Mon Apr  6 21:50:46 2015 DEBUG C_FindObjects()
Mon Apr  6 21:50:46 2015 DEBUG C_FindObjectsFinal()
Mon Apr  6 21:50:46 2015 DEBUG C_Finalize()

which does not really help me. I tried the 0.03 release and the Head-version. No difference.
How can I debug this? Is there a way to figure out if the key generation in hardware worked as expected? Could it be a problem with newer versions of openssh (6.8 and 6.9)?

**Comment by ThomasHabets** [comment]
what does your config look like, and what files are in ~/.simple-tpm-pk11?

**Comment by jdkbx** [comment]
Pretty much as in the example:
$ cat ~/.simple-tpm-pk11/config
key my.key
log foo.log
debug

$ ls ~/.simple-tpm-pk11/
foo.log
my.key

following the command with strace shows that the key file is being read.

**Comment by ThomasHabets** [comment]
I'm assuming the missing config file in the "ls" command is a cut-and-paste error.

What's the output of ssh-keygen -v -D libsimple-tpm-pk11.so ?

You're saying you've tried this with OpenSSH 6.8 and 6.9, and none of them have worked?

**Comment by jdkbx** [comment]
Yes, i forgot the config file. I have configured another system in the same way. A Dell Precision T1600 Desktop with gentoo. Same results.

# tpm_version 
  TPM 1.2 Version Info:
  Chip Version:        1.2.8.28
  Spec Level:          2
  Errata Revision:     3
  TPM Vendor ID:       STM 
  TPM Version:         01010000
  Manufacturer Info:   53544d20

$ ssh-keygen -v -D libsimple-tpm-pk11.so
debug1: manufacturerID <simple-tpm-pk11 manufacturer> cryptokiVersion 0.1 libraryDescription <simple-tpm-pk11 library> libraryVersion 0.1
debug1: label <Simple-TPM-PK11 token> manufacturerID <manuf id> model <model> serial <serial> flags 0x0
no keys
cannot read public key from pkcs11

**Comment by ThomasHabets** [comment]
It works for me with 6.8p1.

You're right that the debug output is not really helpful. I'll work on that. Looking at the code though it seems that something that would cause this is if your key file either doesn't have a 'mod' or an 'exp' line.

Could you verify that you have "exp 010001", "mod ...." and "blob ..." in your keyfile?

**Comment by jdkbx** [comment]
The keyfile looks good to me. stpm-sign does produce good output.

'# Some sort of key.'
'# Key was generated in hardware.'
'exp 010001'
'mod be178a7e3a6f872 ... 12613b81'
'blob 0101000000 ... 13bbe417'

**Comment by ThomasHabets** [comment]
Strange.
What version of gentoo is this? I see they have an X32 version. Is it that one?

I added a couple of debug statements to GetAttributeValues. When all goes well you should be seeing two GetAttributeValues in a row, not just the one that you see:

<pre>
Tue Apr  7 14:03:43 2015 DEBUG C_GetAttributeValue(count=3)
Tue Apr  7 14:03:43 2015 DEBUG    Attribute 0: ID
Tue Apr  7 14:03:43 2015 DEBUG    Attribute 1: Modulus size 256
Tue Apr  7 14:03:43 2015 DEBUG    Attribute 2: Exponent size 3
Tue Apr  7 14:03:43 2015 DEBUG C_GetAttributeValue(count=3)
Tue Apr  7 14:03:43 2015 DEBUG    Attribute 0: ID
Tue Apr  7 14:03:43 2015 DEBUG    Attribute 1: Modulus size 256
Tue Apr  7 14:03:43 2015 DEBUG    Attribute 2: Exponent size 3
</pre>

**Comment by jdkbx** [comment]
No, its a standard amd64 (x86_64).

I guess we are getting closer:
Tue Apr  7 15:07:17 2015 DEBUG C_GetFunctionList
Tue Apr  7 15:07:17 2015 DEBUG C_Initialize
Tue Apr  7 15:07:17 2015 DEBUG C_GetInfo
Tue Apr  7 15:07:17 2015 DEBUG C_GetSlotList
Tue Apr  7 15:07:17 2015 DEBUG C_GetSlotList
Tue Apr  7 15:07:17 2015 DEBUG C_GetTokenInfo
Tue Apr  7 15:07:19 2015 DEBUG C_OpenSession
Tue Apr  7 15:07:19 2015 DEBUG C_FindObjectsInit
Tue Apr  7 15:07:19 2015 DEBUG C_FindObjects
Tue Apr  7 15:07:19 2015 DEBUG C_GetAttributeValue(count=3)
Tue Apr  7 15:07:19 2015 DEBUG    Attribute 0: ID
Tue Apr  7 15:07:19 2015 DEBUG C_FindObjects
Tue Apr  7 15:07:19 2015 DEBUG C_FindObjectsFinal
Tue Apr  7 15:07:19 2015 DEBUG C_Finalize

**Comment by ThomasHabets** [comment]
I just uploaded another one. Are you sure you're showing everything there? OpenSSH will first try pubkeys, and then certificates. Hmm... with a two second pause I assume that's what's happening.

Could you do another pull? I added a couple of more outputs.

**Comment by jdkbx** [comment]
It seems openssh is not looking for pubkeys in my case.

Tue Apr  7 15:15:17 2015 DEBUG C_GetFunctionList
Tue Apr  7 15:15:17 2015 DEBUG C_Initialize
Tue Apr  7 15:15:17 2015 DEBUG C_GetInfo
Tue Apr  7 15:15:17 2015 DEBUG C_GetSlotList
Tue Apr  7 15:15:17 2015 DEBUG C_GetSlotList
Tue Apr  7 15:15:17 2015 DEBUG C_GetTokenInfo
Tue Apr  7 15:15:18 2015 DEBUG C_OpenSession
Tue Apr  7 15:15:18 2015 DEBUG C_FindObjectsInit
Tue Apr  7 15:15:18 2015 DEBUG C_FindObjects
Tue Apr  7 15:15:18 2015 DEBUG C_GetAttributeValue(count=3)
Tue Apr  7 15:15:18 2015 DEBUG    Attribute 0: ID
Tue Apr  7 15:15:18 2015 DEBUG    Attribute 1: Subject (unsupported)
Tue Apr  7 15:15:18 2015 DEBUG    Attribute 2: Value (unsupported)
Tue Apr  7 15:15:18 2015 DEBUG C_FindObjects
Tue Apr  7 15:15:18 2015 DEBUG C_FindObjectsFinal
Tue Apr  7 15:15:18 2015 DEBUG C_Finalize

**Comment by jdkbx** [comment]
I just recompiled ssh without support for X509 certificates and it worked. Somehow that X509 support patch interferes with the order of expected operations. I try to look into this, but the patch alone has 29K LOCs. http://roumenpetrov.info/openssh/
In any case, thanks for your support and time.

**Comment by ThomasHabets** [comment]
Ah, is the version shipped with gentoo (or whatever version you ran) a patched version?

Yeah, that would do it. it seems the patch you linked to disables public keys. ssh-pkcs11.c line 601:
<pre>
#ifdef USE_LEGACY_PKCS11_RSAKEY
        if (pkcs11_fetch_keys_filter(p, slotidx, pubkey_filter, 1, pubkey_attribs,
            keysp, nkeys) < 0 ||
#else
        (void)pubkey_filter;
        (void)pubkey_attribs;
        if (
#endif
            pkcs11_fetch_keys_filter(p, slotidx, cert_filter, sizeof(cert_filter)/sizeof(*cert_filter),
            cert_attribs, keysp, nkeys) < 0)
                return (-1);
</pre>

**Comment by ThomasHabets** [comment]
Seems like a kinda lazy approach to not allow the old kind of keys.

Any reason you're using X509 instead of [OpenSSH certificates](https://blog.habets.se/2011/07/OpenSSH-certificates)? (yes, OpenSSH certificates are more limited, so if you need e.g. multilevel CA's then that would be a reason)

**Comment by jdkbx** [comment]
Yes, it had the patch applied. No reason really, just how i decided to configured this system (obviously a mistake). I will make your software in gentoo depend on openssh without that patch.
