### ISSUE TITLE
Problems with openssh >= 7.0

### ISSUE THREAD

**Issue by tkolo** [ThomasHabets/simple-tpm-pk11#21]
After upgrading openssh to 7.0 this module no longer works
```
$ ssh-keygen -D libsimple-tpm-pk11.so -vvvv
debug1: manufacturerID <simple-tpm-pk11 manufacturer> cryptokiVersion 0.1 libraryDescription <simple-tpm-pk11 library> libraryVersion 0.1
debug2: pkcs11_add_provider: ignoring uninitialised token in slot 0
no keys
cannot read public key from pkcs11
```

**Comment by ThomasHabets** [comment]
Try recompiling simple-tpmpk11. There was an abi change. I'll look at this
more when at computer.

**Comment by tkolo** [comment]
Unfortunately that didn't help.

**Comment by tkolo** [comment]
Also, I'm using release 0.03, not the master branch, should I try building newest master or it doesn't really matter?

**Comment by ThomasHabets** [comment]
It shouldn't matter, so this is probably something else.

**Comment by ThomasHabets** [comment]
I'm unable to reproduce this on an Ubuntu system, downloading OpenSSH 7.0 and 7.1 from http://www.mirrorservice.org/pub/OpenBSD/OpenSSH/portable/

It sounds like whatever OpenSSH package you've installed is not compatible with the opencryptoki library you have installed.

Where did you get OpenSSH, and where did you get your opencryptoki library?

Could you compare `CK_TOKEN_INFO` in `/usr/include/opencryptoki/pkcs11types.h` and `struct ck_token_info` in OpenSSH `pkcs11.h`?

**Comment by ThomasHabets** [comment]
Oh no, my mistake. Yes, please use the master branch. That's probably the problem.

I'll tag the current HEAD as 0.04 later today.

**Comment by tkolo** [comment]
Compiling latest master fixed the problem. Thanks a lot!

**Comment by ThomasHabets** [comment]
Thanks for confirming. Version 0.04 now released.
