### ISSUE TITLE
Extracting public key fails

### ISSUE THREAD

**Issue by Cavka** [ThomasHabets/simple-tpm-pk11#25]
Creating and signing works fine but when I try to extract the public key in SSH format I get:

>~/.simple-tpm-pk11$ ssh-keygen -D libsimple-tpm-pk11.so
>C_GetTokenInfo failed: 6
>no keys
>cannot read public key from pkcs11

Can it be related to the fact that I have SRK password set? The log is empty and my config is:

>~/.simple-tpm-pk11$ ls
>config  key.log  ssh.key
>~/.simple-tpm-pk11$ cat config 
>key ssh.key
>log key.log

**Comment by ThomasHabets** [comment]
Yes. You'll need to set "srk_pin foo bar baz" in your ~/.simple-tpm-pk11/config.

IIRC there's no way to make OpenSSH ask for the SRK.

Try that.

I guess I could add support for shelling out to "ssh-askpass" or something to get the SRK.

**Comment by Cavka** [comment]
Yep, that was it, thanks! And yes, an option to get the SRK would be great.

**Comment by ThomasHabets** [comment]
Is it really an SRK PIN you want, though, or is it a key PIN?

The SRK PIN is only your access token to be allowed to use the TPM chip. What you actually want is probably to generate the key with the "-p" option to stpm-keygen. That prompt is already built in.

**Comment by Cavka** [comment]
Yep, I know about the "-p" option. And it is really the SRK PIN I want, something exactly like the -p option in stpm-keygen would be awesome (that was what I was initially looking for when trying to extract the public key).

**Comment by ThomasHabets** [comment]
Filed a separate feature request. But I still question the need for it. Could you elaborate on the use case where it's a danger that someone can perform TPM operations, and it's so dangerous that you want to protect the access better than just a password stored in a file in your home directory?

**Comment by Cavka** [comment]
i.e. your server gets compromised, without the SRK PIN set the adversary automatically has access to your private ssh keys and possibly to other servers without any effort. With the PIN set, you can at least make follow-up attacks more difficult. It's more about defense-in-depth - putting as many obstacles on the way as possible.

**Comment by ThomasHabets** [comment]
How is the SRK PIN more effective in protecting the keys or other access than a key PIN? Or do you mean both? What value does the SRK PIN add over key PIN?

**Comment by Cavka** [comment]
Maybe I misunderstood something but it is the SRK PIN that allows your to unseal your private SSH key, right? You would never use your owner password to do so?

**Comment by ThomasHabets** [comment]
Owner password is to administer the TPM chip. SRK PIN is the password that allows the TPM to do operations, and is not specific to any one private SSH key. Key PIN is "private SSH key" specific. Both are needed to use a key. Maybe it now makes sense why it's fine if SRK PIN is the "well known secret".

To put it another way:
The key blob on disk (~/.simple-tpm-pk11/my.key) is protected by the SRK and optionally a key PIN.
The SRK (inside the TPM) is optionally protected by another PIN, the SRK PIN.

So to do operations you need SRK PIN, the key blob, and the key PIN. Both PINs are optional to set, but PINs that are set need to be provided to do operations.

And to be clear: When I say "protected by", this protects operations ("here, sign this for me"). There's no way to extract key material unless you use the -S option. I forget which PINs you need to extract keys you generate with -S, but it could be the owner PIN, SRK PIN, *and* key PIN.
