### ISSUE TITLE
Make ssh-add work, and/or document how to make it work

### ISSUE THREAD

**Issue by ThomasHabets** [ThomasHabets/simple-tpm-pk11#30]
```
$ ssh-add -s /…/libsimple-tpm-pk11.so
Enter passphrase for PKCS#11: 
Could not add card "/…/libsimple-tpm-pk11.so": agent refused operation
```

**Comment by ThomasHabets** [comment]
```
$ ./configure  --prefix=$HOME/opt/openssh
[…]
$ grep -q '^#define ENABLE_PKCS11' config.h && echo success || echo fail
success
$ sudo mkdir -p /var/empty
$ make install
[…]
$ ~/opt/openssh/bin/ssh-agent
[… env stuff for ssh-agent. copy-paste run this …]
$ ssh-add -s /usr/local/lib/libsimple-tpm-pk11.soEnter passphrase for PKCS#11: 
Card added: /usr/local/lib/libsimple-tpm-pk11.so
$ ssh-add -l
2048 SHA256:xxxxx[…]xxxxxx /usr/local/lib/libsimple-tpm-pk11.so (RSA)
```

**Comment by ThomasHabets** [comment]
In conclusion: this is not a problem with simple-tpm-pk11, but with OpenSSH on my system (and presumably others) not being built with PKCS11 support for `ssh-agent`. That's strange since the `ssh` binary works just fine. I guess `ssh` didn't `#ifdef` away any cases in a switch statement, so it just happened to work.

I should contact upstream.

**Comment by qistoph** [comment]
Rebuilding ssh-agent as described indeed solves the problem and makes my TPM based key available in ssh-agent.

Ubuntu 16.04

**Comment by ThomasHabets** [comment]
@qistoph 
I don't have a pure enough Ubuntu system. Could you follow https://help.ubuntu.com/community/ReportingBugs to report this as a bug?

**Comment by qistoph** [comment]
Done: [Ubuntu bug 1606929](https://bugs.launchpad.net/ubuntu/+source/openssh/+bug/1606929).

**Comment by qistoph** [comment]
Actually I just discovered that ssh-agent wasn't used by default, but gnome-keyring-daemon is. Probably gnome-keyring-daemon just does not support PKCS#11 yet...

If I run ssh-agent, without recompiling, it also works.
```
$ /usr/bin/ssh-agent
[… env stuff for ssh-agent. copy-paste run this …]
$ ssh-add -s /usr/local/lib/libsimple-tpm-pk11.so
Enter passphrase for PKCS#11: 
Card added: /usr/local/lib/libsimple-tpm-pk11.so
$ ssh-add -l
2048 SHA256:xxxxx[…]xxxxxx /usr/local/lib/libsimple-tpm-pk11.so (RSA)
```

**Comment by ThomasHabets** [comment]
I'm going to assume every case has been gnome-keyring. Closing after documenting.
