### ISSUE TITLE
Missing information about configure file

### ISSUE THREAD

**Issue by mareksabo** [ThomasHabets/simple-tpm-pk11#33]
Hi,

I would like to use your SW, but I'm not sure how to build your app - you don't have any default configure file and I simply don't know how it should look like. I tried to run bootstrap.sh script which created the configure file, but then it started to complain about missing files in m4 directory: `configure: error: cannot find install-sh, install.sh, or shtool in m4 "."/m4
` 

I tried to run following commands:

    aclocal # Set up an m4 environment
    autoconf # Generate configure from configure.ac
    automake --add-missing # Generate Makefile.in from Makefile.am
    ./configure # Generate Makefile from Makefile.in`

but running configure stopped working on:

    checking whether to enable maintainer-specific portions of Makefiles... no
    ./configure: line 2887: syntax error near unexpected token `dlopen'
    ./configure: line 2887: `LT_INIT(dlopen)'

Could you plese add some additional information about creating configure file?

Thank you,
Marek

**Comment by ThomasHabets** [comment]
The standard way to create configure is to run `./bootstrap.sh`.

**Comment by mareksabo** [comment]
Thank you! I was missing `libtool`, that's why it was not working.
