### ISSUE TITLE
Debian package dependencies

### ISSUE THREAD

**Issue by pete-theobald** [ThomasHabets/simple-tpm-pk11#41]
Hi, This is a suggestion, not an issue.
Can the follwoing packages `apt-get install tpm-tools libtspi-dev libopencryptoki-dev libssl-dev` be added as requirements to the debian package? Or at least recommendations. Installing simple-tpm-pk11 is very simple from the instructions on here (github) but not obvious when installed using apt-get.
Regards
Peter

**Comment by ThomasHabets** [comment]
You don't need the `-dev` packages if you install with `apt-get`. And the Debian package [does have a list](https://packages.debian.org/stretch/simple-tpm-pk11) of dependencies already. What exactly is not working, or is hard, when using apt-get?

**Comment by pete-theobald** [comment]
Hi thomas. I hot an error saying it could not connect to tcsd. When i ran
that aptget command it resolved that. Sounds a bit strange. Im happy to
investigate further later today.
Regards
Peter

**Comment by ThomasHabets** [comment]
`tcsd` is part of `trousers`, so it should be correct.

I'm closing this, but feel free to reopen if you have a reproducible case.
