### ISSUE TITLE
stpm-verify fails when built against openssl 1.1

### ISSUE THREAD

**Issue by IanSMiller** [ThomasHabets/simple-tpm-pk11#43]
When run using openssl 1.1, stpm-verify always reports:-
"stpm-verify: Exception: RSA_set0_key failed"

In function public_decrypt() [common.cc line 761] the code reads:-

  if (RSA_set0_key(rsa.get(), string2bn(key.modulus), string2bn(key.exponent),
                   NULL)) {
    throw std::runtime_error("RSA_set0_key failed");
  }
However the man page for RSA_set0_key states:-
"RSA_set0_key(), RSA_set0_factors and RSA_set0_crt_params() return 1 on success or 0 on failure."
If RSA_set0_key returns 1 (success) the exception is thrown.  This works with in-line version for openssl 1.0, [lines 55 to 61] because that returns 0,

I think the following will fix this:-

```
--- common.cc	2017-10-24 20:06:31.000000000 +0100
+++ common.cc.new	2018-08-02 12:25:03.433722093 +0100
@@ -57,7 +57,7 @@
   rsa->n = n;
   rsa->e = e;
   rsa->d = d;
-  return 0;
+  return 1;
 }
 #endif
 #ifndef HAVE_RSA_GET0_KEY
@@ -758,7 +758,7 @@
 {
   // Load key.
   RSAWrap rsa;
-  if (RSA_set0_key(rsa.get(), string2bn(key.modulus), string2bn(key.exponent),
+  if (!RSA_set0_key(rsa.get(), string2bn(key.modulus), string2bn(key.exponent),
                    NULL)) {
     throw std::runtime_error("RSA_set0_key failed");
   }
```

**Comment by ThomasHabets** [comment]
Thanks!
